### ISSUE TITLE
70x70 PatchGAN

### ISSUE THREAD

**Issue by liuwei16** [yueruchen/Pedestrian-Synthesis-GAN#1]
Dear Yifan,
It is my great interest to read your encouranging paper, but I am still confused with several implementataions with Pedestrian-Synthesis-GAN, such as where is the 70x70 PatchGAN in this code.
How can I concact with you? 
My email: liuwei16@nudt.edu.cn
Thank you very much.

Best,
Wei

**Comment by yueruchen** [comment]
Previous network often use fully connected layer or FCN to make the output of network be one neuron. On this task we just get NxN neuron at the output of network instead of using fully connected layer, which is called PatchGAN.

I don't clearly remember the value of N here. It depends on the inout image size.

Thanks,
